/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplateIndexRouteImport } from './routes/template/index'
import { Route as SessionIndexRouteImport } from './routes/session/index'
import { Route as BotIndexRouteImport } from './routes/bot/index'
import { Route as TemplateWizardRouteImport } from './routes/template/wizard'
import { Route as TemplateNewRouteImport } from './routes/template/new'
import { Route as TemplateIdRouteImport } from './routes/template/$id'
import { Route as SessionNewRouteImport } from './routes/session/new'
import { Route as SessionIdRouteImport } from './routes/session/$id'
import { Route as BotNewRouteImport } from './routes/bot/new'
import { Route as TemplateIdStepsRouteImport } from './routes/template/$id.steps'
import { Route as SessionIdStepsRouteImport } from './routes/session/$id.steps'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIndexRoute = TemplateIndexRouteImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotIndexRoute = BotIndexRouteImport.update({
  id: '/bot/',
  path: '/bot/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateWizardRoute = TemplateWizardRouteImport.update({
  id: '/template/wizard',
  path: '/template/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateNewRoute = TemplateNewRouteImport.update({
  id: '/template/new',
  path: '/template/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIdRoute = TemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionNewRoute = SessionNewRouteImport.update({
  id: '/session/new',
  path: '/session/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BotNewRoute = BotNewRouteImport.update({
  id: '/bot/new',
  path: '/bot/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIdStepsRoute = TemplateIdStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => TemplateIdRoute,
} as any)
const SessionIdStepsRoute = SessionIdStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => SessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bot/new': typeof BotNewRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/new': typeof SessionNewRoute
  '/template/$id': typeof TemplateIdRouteWithChildren
  '/template/new': typeof TemplateNewRoute
  '/template/wizard': typeof TemplateWizardRoute
  '/bot/': typeof BotIndexRoute
  '/session/': typeof SessionIndexRoute
  '/template/': typeof TemplateIndexRoute
  '/session/$id/steps': typeof SessionIdStepsRoute
  '/template/$id/steps': typeof TemplateIdStepsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bot/new': typeof BotNewRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/new': typeof SessionNewRoute
  '/template/$id': typeof TemplateIdRouteWithChildren
  '/template/new': typeof TemplateNewRoute
  '/template/wizard': typeof TemplateWizardRoute
  '/bot': typeof BotIndexRoute
  '/session': typeof SessionIndexRoute
  '/template': typeof TemplateIndexRoute
  '/session/$id/steps': typeof SessionIdStepsRoute
  '/template/$id/steps': typeof TemplateIdStepsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bot/new': typeof BotNewRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/new': typeof SessionNewRoute
  '/template/$id': typeof TemplateIdRouteWithChildren
  '/template/new': typeof TemplateNewRoute
  '/template/wizard': typeof TemplateWizardRoute
  '/bot/': typeof BotIndexRoute
  '/session/': typeof SessionIndexRoute
  '/template/': typeof TemplateIndexRoute
  '/session/$id/steps': typeof SessionIdStepsRoute
  '/template/$id/steps': typeof TemplateIdStepsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bot/new'
    | '/session/$id'
    | '/session/new'
    | '/template/$id'
    | '/template/new'
    | '/template/wizard'
    | '/bot/'
    | '/session/'
    | '/template/'
    | '/session/$id/steps'
    | '/template/$id/steps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bot/new'
    | '/session/$id'
    | '/session/new'
    | '/template/$id'
    | '/template/new'
    | '/template/wizard'
    | '/bot'
    | '/session'
    | '/template'
    | '/session/$id/steps'
    | '/template/$id/steps'
  id:
    | '__root__'
    | '/'
    | '/bot/new'
    | '/session/$id'
    | '/session/new'
    | '/template/$id'
    | '/template/new'
    | '/template/wizard'
    | '/bot/'
    | '/session/'
    | '/template/'
    | '/session/$id/steps'
    | '/template/$id/steps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotNewRoute: typeof BotNewRoute
  SessionIdRoute: typeof SessionIdRouteWithChildren
  SessionNewRoute: typeof SessionNewRoute
  TemplateIdRoute: typeof TemplateIdRouteWithChildren
  TemplateNewRoute: typeof TemplateNewRoute
  TemplateWizardRoute: typeof TemplateWizardRoute
  BotIndexRoute: typeof BotIndexRoute
  SessionIndexRoute: typeof SessionIndexRoute
  TemplateIndexRoute: typeof TemplateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/': {
      id: '/template/'
      path: '/template'
      fullPath: '/template/'
      preLoaderRoute: typeof TemplateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/session'
      fullPath: '/session/'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot/': {
      id: '/bot/'
      path: '/bot'
      fullPath: '/bot/'
      preLoaderRoute: typeof BotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/wizard': {
      id: '/template/wizard'
      path: '/template/wizard'
      fullPath: '/template/wizard'
      preLoaderRoute: typeof TemplateWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/new': {
      id: '/template/new'
      path: '/template/new'
      fullPath: '/template/new'
      preLoaderRoute: typeof TemplateNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$id': {
      id: '/template/$id'
      path: '/template/$id'
      fullPath: '/template/$id'
      preLoaderRoute: typeof TemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/new': {
      id: '/session/new'
      path: '/session/new'
      fullPath: '/session/new'
      preLoaderRoute: typeof SessionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot/new': {
      id: '/bot/new'
      path: '/bot/new'
      fullPath: '/bot/new'
      preLoaderRoute: typeof BotNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$id/steps': {
      id: '/template/$id/steps'
      path: '/steps'
      fullPath: '/template/$id/steps'
      preLoaderRoute: typeof TemplateIdStepsRouteImport
      parentRoute: typeof TemplateIdRoute
    }
    '/session/$id/steps': {
      id: '/session/$id/steps'
      path: '/steps'
      fullPath: '/session/$id/steps'
      preLoaderRoute: typeof SessionIdStepsRouteImport
      parentRoute: typeof SessionIdRoute
    }
  }
}

interface SessionIdRouteChildren {
  SessionIdStepsRoute: typeof SessionIdStepsRoute
}

const SessionIdRouteChildren: SessionIdRouteChildren = {
  SessionIdStepsRoute: SessionIdStepsRoute,
}

const SessionIdRouteWithChildren = SessionIdRoute._addFileChildren(
  SessionIdRouteChildren,
)

interface TemplateIdRouteChildren {
  TemplateIdStepsRoute: typeof TemplateIdStepsRoute
}

const TemplateIdRouteChildren: TemplateIdRouteChildren = {
  TemplateIdStepsRoute: TemplateIdStepsRoute,
}

const TemplateIdRouteWithChildren = TemplateIdRoute._addFileChildren(
  TemplateIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotNewRoute: BotNewRoute,
  SessionIdRoute: SessionIdRouteWithChildren,
  SessionNewRoute: SessionNewRoute,
  TemplateIdRoute: TemplateIdRouteWithChildren,
  TemplateNewRoute: TemplateNewRoute,
  TemplateWizardRoute: TemplateWizardRoute,
  BotIndexRoute: BotIndexRoute,
  SessionIndexRoute: SessionIndexRoute,
  TemplateIndexRoute: TemplateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
